---
- name: 0.系统初始化
  gather_facts: false
  hosts: newnode 
  roles:
    - common
  tags: common 

- name: 1.部署Docker
  gather_facts: false
  hosts: newnode
  roles:
    - docker 
  tags: docker

- name: 2.部署K8S Node
  gather_facts: false
  hosts: newnode
  roles:
    - node
  tags: node
# 增加master节点同意node加入集群
- name: 允许Node加入集群
  gather_facts: false
  hosts: master
  ignore_errors: yes
  shell: kubectl certificate approve $(kubectl get csr |awk 'NR!=1{print $1}')