---
# 这个剧本在所有节点上运行

- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no

- name: 关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
  
- name: 关闭swap
  lineinfile:
    dest: /etc/fstab
    regexp: "UUID.*swap"
    line: ""

- name: 即时生效
  shell: setenforce 0 ; swapoff -a

- name: 拷贝时区
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: 添加hosts
  template: src=hosts.j2 dest=/etc/hosts

- name: 修改内核参数，保证flannel和coredns网络正常，且调整ipvs模块的table full
  copy: src=k8s.conf  dest=/etc/sysctl.d/k8s.conf

- name: 使内核参数修改生效
  shell: sysctl -p /etc/sysctl.d/k8s.conf

- name: 添加内核模块，开启ipvs模式
  copy: src=ipvs.modules  dest=/etc/sysconfig/modules/  mode=0755

- name: 加载内核模块
  shell: bash /etc/sysconfig/modules/ipvs.modules && lsmod | grep -e ip_vs -e nf_conntrack

- name: 安装常用软件
  yum: name={{ item }} state=present
  with_items:
    - "ipset"
    - "ipvsadm"
    - "ntpdate"
    - "bash-completion"

- name: 关闭ntpd服务
  service: name=ntpd state=stopped enabled=no

- name: 同步系统时间
  shell: ntpdate ntp.aliyun.com

